version: '3.7'
services:
  notebook:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
     - ~/Documents/GitHub/bah-facial-recognition/jetson:/app
    # devices:
    # - /dev/video0:/dev/video0